### ISSUE TITLE
Сatberry plugin highlights all custom attributes in cat-comp tag

### ISSUE THREAD

**Issue by old-graff** [catberry/catberry-idea-plugin#12]
After install catberry-idea-plugin webstorm highlights all custom attributes in cat-comp tag.

**Comment by old-graff** [comment]
![image](https://cloud.githubusercontent.com/assets/628086/14521912/fcb89688-023c-11e6-92aa-8a8957a589c1.png)

**Comment by prokofiev** [comment]
This is a normal behavior of the IDE. You can disable the plug-in and make sure that in all known for WebStorm html-tags, the behavior will be the same.
